#!/usr/bin/perl

#!/usr/bin/perl

open(IN, "curl 'http://maps.kittelson.com/OaklandCounts' |");
while (<IN>) {
        $kml .= $_;
}
close(IN);

while ($kml =~ s/(http:\/\/maps.kittelson.com\/system\/uploads\/[0-9]+\/original\/(TMC_...KML))//) {
        $url = $1;
	$base = $2;

	print "$url\n";
	system "curl -O '$url'";

	open(IN, "$base");
	while (<IN>) {
		while (s/"(https:\/\/googledrive.com[^"]*)"//) {
			$url = $1;
			print "$url\n";
			$url =~ s/'/%27/g;
			$url =~ s/ /%20/g;

			if ($url =~ /(.*)(TMC_.*)/) {
				$p1 = $1;
				$p2 = $2;
				$p2 =~ s/\//_/g;
				$url = "$p1$p2";
			}

			$base = $url;
			$base =~ s/.*\///;
			next if -f $base;

			system "curl -L -O '$url'";
		}
	}
}
