#!/usr/bin/perl

system "curl -O http://www.oaklandbikemaps.info/counts/layers/counts.kmz";
mkdir "pdf";

open(OUT, ">index.csv");
open(IN, "unzip -c counts.kmz |");
while (<IN>) {
	if (/<coordinates>([0-9-.]+),([0-9-.]+)/) {
		$lon = $1;
		$lat = $2;
	}

	if (/<name>([^<]*)/) {
		$name = $1;
		$name =~ s/,/ /g;
	}

	if (/<a href="([^"]*)/) {
		$url = $1;
	}

	if (/<\/Placemark>/) {
		if ($url =~ /([0-9]+).pdf/) {
			$id = $1;
			print OUT "$id,$lat,$lon,$url,$name\n";

			if (1 || ! -s "pdf/$id.pdf") {
				system "curl -q -o pdf/$id.pdf '$url'";
			}

			system "cd pdf; pdftotext -layout $id.pdf";
		}

		$lat = $lon = $id = $url = $name = "";
	}
}
